add_newline = false

[character]
error_symbol = "[Â»](bold green)"
success_symbol = "[Â»](bold green)"
vicmd_symbol = "[Â«](bold green)"

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "bold red"
style_user = "blue yellow"

[hostname]
disabled = false
format = "[@$hostname]($style)"
ssh_only = false
style = "bold dimmed green"

[directory]
disabled = false
format = "[:$path]($style)"
style = "bold cyan"
truncate_to_repo = false
truncation_length = 10

[git_branch]
format = "[ $symbol$branch]($style)"
style = "bold purple"

[git_commit]
only_detached = false
tag_disabled = false
tag_symbol = ":"
format = "[\\($hash$tag\\)]($style)"

[git_status]
ahead = "â‡¡($count)"
behind = "â‡£($count)"
conflicted = "ğŸ³"
diverged = "â‡•â‡¡($ahead_count)â‡£($behind_count)"
format = '([\[$all_status$ahead_behind\]]($style) )'
modified = "ğŸ“"
staged = "[++($count)](green)"
stashed = "ğŸ“¦"
style = " bold yellow"
untracked = "ğŸ¤·"
up_to_date = "âœ“"

[nix_shell]
format = "[ $symbol  $name ]($style)"
style = "bold blue"
symbol = "â„ï¸"

[python]
disabled = true

[cmake]
disabled = true


