add_newline = false

[character]
error_symbol = "[Â»](bold green)"
success_symbol = "[Â»](bold green)"
vicmd_symbol = "[Â«](bold green)"

[cmake]
disabled = true

[directory]
disabled = false
format = "[:$path]($style)"
style = "bold cyan"
truncate_to_repo = false
truncation_length = 10

[git_branch]
format = "[ $symbol$branch]($style)"
style = "bold purple"

[git_status]
ahead = "â‡¡($count)"
behind = "â‡£($count)"
conflicted = "ğŸ³"
diverged = "â‡•â‡¡($ahead_count)â‡£($behind_count)"
format = "[ $all_status]($style)"
modified = "ğŸ“"
staged = "[++($count)](green)"
stashed = "ğŸ“¦"
style = " bold yellow"
untracked = "ğŸ¤·"
up_to_date = "âœ“"

[hostname]
disabled = false
format = "[@$hostname]($style)"
ssh_only = false
style = "bold dimmed green"

[nix_shell]
format = "[ $symbol  $name ]($style)"
style = "bold blue"
symbol = "â„ï¸"

[python]
disabled = true

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_root = "bold red"
style_user = "blue yellow"
